name: CLI end to end test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install using pip
          run: |
            pip install -e .