name: CLI end to end test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install using pip
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run e2e test
        run: |
          cd e2e
          libij -h
          libij main1.cpp -L lib1 --no-color > test1.out && diff test1.out test1.ans --ignore-blank-lines
          libij main1.cpp -L lib1 -o test2.out && diff test2.out test1.ans
