name: AOJ System Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install online judge tools
        run: |
          python -m pip install --upgrade pip
          pip install -U online-judge-tools
          which oj
      - name: Install using Pip
        run: |
          pip install -e .[develop]
      - name: System Test
        run: |
          mkdir -p $DIR
          oj download --system "$URL" -d $DIR
          oj test -c $BIN -d $DIR
        env:
          BIN: GRL_4_B
          DIR: /aoj/GRL_4_B
          URL: http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=GRL_4_B


