name: AOJ System Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install using Pip
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Install online judge tools
        run: |
          pip install online-judge-tools
          which oj
      - name: Setup testcases
        run: |
          mkdir -p $DIR
          oj download --system "$URL" -d $DIR
        env:
          DIR: aoj/GRL_4_B
          URL: http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=GRL_4_B
      - name: System Test
        run: |
          oj test -c $BIN -d $DIR --judge-command $JDG -s -j 4
        env:
          BIN: GRL_4_B
          JDG: GRL_4_B_JUDGE
          DIR: aoj/GRL_4_B
